apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payments
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: shop-platform

  source:
    repoURL: https://github.com/CHANGE_ME/03-eks-microservices-gitops.git
    targetRevision: main
    path: charts/service-chart
    helm:
      releaseName: payments
      values: |
        nameOverride: payments
        fullnameOverride: payments
        image:
          repository: <ACCOUNT_ID>.dkr.ecr.eu-west-3.amazonaws.com/shop-platform/payments
          tag: v0.1.0
        containerPort: 8000
        service:
          port: 80
        serviceAccount:
          create: true
          name: payments
          annotations:
            # ARN du rôle IRSA (output Terraform payments_role_arn).
            eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/shop-platform-dev-payments
        podSecurityContext:
          runAsNonRoot: true
          runAsUser: 999
          fsGroup: 999
          seccompProfile:
            type: RuntimeDefault
        autoscaling:
          enabled: true
          minReplicas: 2
          maxReplicas: 12
          targetCPUUtilizationPercentage: 60
        ingress:
          enabled: false
        networkPolicy:
          enabled: true
          ingressFrom:
            - podSelector:
                matchLabels:
                  app.kubernetes.io/name: api-gateway

  destination:
    server: https://kubernetes.default.svc
    namespace: payments

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
